PROCESSOR_LIST_FILE = "records.pickle"

# Set following environment variable before importing the Safety Guard client
SAFETY_GUARD_UPDATE_INTERVAL_SEC = 30
EXECUTOR_HEALTH_CHECK_INTERVAL_SEC = 30
EXECUTOR_HEALTH_CHECK_TIMEOUT_SEC = 10
EXECUTOR_HEALTH_CHECK_RETRIES = 5
EXECUTOR_HEALTH_CHECK_START_PERIOD_SEC = 30

# routes/chat.py
COMPLETION_TIMEOUT = 5000
RESPONSE_CACHE_ENABLED = False
