services:
  llama3_1-executor:
    image: skyscopeai/model-executor
    environment:
      EXECUTOR_TYPE: llamacpp
      EXECUTOR_ACCESS_CODE: .model/meta-llama/llama-3.1-8b
      EXECUTOR_NAME: Meta LLaMA3.1 8B Instruct
      EXECUTOR_IMAGE: llama3_1.jpeg # Refer to src/multi-chat/public/images
      # HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
    depends_on:
      - executor-builder
      - kernel
      - multi-chat
    command: [
      "--model_path", "hf://chatpdflocal/llama3.1-8b-gguf?ggml-model-Q4_K_M.gguf",
      "--no_system_prompt", "--stop", "<|eot_id|>"
    ]
    restart: unless-stopped
    volumes: ["~/.cache/huggingface:/root/.cache/huggingface"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    networks: ["backend"]