<?php

namespace App\Enums;

/**
 * Fixed, machine-readable status codes for API JSON responses.
 * Each case corresponds 1:1 with a translation key in lang/{locale}/api.php,
 * so API clients can branch on status without depending on the
 * (localized) message text.
 */
enum ApiStatusCode: string
{
    case AUTH_FAILED = 'AUTH_FAILED';
    case NO_PERMISSION = 'NO_PERMISSION';
    case NO_PERMISSION_GENERIC = 'NO_PERMISSION_GENERIC';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case FORBIDDEN = 'FORBIDDEN';
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case ACCOUNT_DISABLED = 'ACCOUNT_DISABLED';
    case PERMISSION_DENIED = 'PERMISSION_DENIED';
    case USER_NOT_FOUND = 'USER_NOT_FOUND';
    case GROUP_NOT_FOUND = 'GROUP_NOT_FOUND';
    case ROOM_NOT_FOUND = 'ROOM_NOT_FOUND';
    case BOT_NOT_FOUND = 'BOT_NOT_FOUND';
    case MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND';
    case FEEDBACK_NOT_FOUND = 'FEEDBACK_NOT_FOUND';
    case FILE_NOT_FOUND = 'FILE_NOT_FOUND';
    case BOTS_NO_PERMISSION_VISIBILITY = 'BOTS_NO_PERMISSION_VISIBILITY';
    case BOTS_BASE_MODEL_NOT_FOUND = 'BOTS_BASE_MODEL_NOT_FOUND';
    case BOTS_SELECTED_BASE_MODEL_NOT_FOUND = 'BOTS_SELECTED_BASE_MODEL_NOT_FOUND';
    case BOTS_NO_PERMISSION_MODEL = 'BOTS_NO_PERMISSION_MODEL';
    case BOTS_NO_PERMISSION_UPDATE = 'BOTS_NO_PERMISSION_UPDATE';
    case BOTS_NO_PERMISSION_DELETE = 'BOTS_NO_PERMISSION_DELETE';
    case BOTS_CREATED = 'BOTS_CREATED';
    case BOTS_UPDATED = 'BOTS_UPDATED';
    case BOTS_DELETED = 'BOTS_DELETED';
    case ROOMS_BOT_NOT_FOUND_OR_INACCESSIBLE = 'ROOMS_BOT_NOT_FOUND_OR_INACCESSIBLE';
    case ROOMS_CREATE_WITH_PROMPT_FAILED = 'ROOMS_CREATE_WITH_PROMPT_FAILED';
    case ROOMS_NO_PERMISSION_ACCESS = 'ROOMS_NO_PERMISSION_ACCESS';
    case ROOMS_UNAUTHORIZED_ACCESS = 'ROOMS_UNAUTHORIZED_ACCESS';
    case ROOMS_ABORTED = 'ROOMS_ABORTED';
    case ROOMS_HISTORY_DATA_REQUIRED = 'ROOMS_HISTORY_DATA_REQUIRED';
    case ROOMS_NO_VALID_HISTORY_DATA = 'ROOMS_NO_VALID_HISTORY_DATA';
    case ROOMS_NO_VALID_BOTS_OR_ROOM = 'ROOMS_NO_VALID_BOTS_OR_ROOM';
    case ROOMS_IMPORT_SUCCESS = 'ROOMS_IMPORT_SUCCESS';
    case ROOMS_NO_VALID_HISTORY_TO_IMPORT = 'ROOMS_NO_VALID_HISTORY_TO_IMPORT';
    case ROOMS_IMPORT_ERROR_PREFIX = 'ROOMS_IMPORT_ERROR_PREFIX';
    case ROOMS_INVALID_JSON_BODY = 'ROOMS_INVALID_JSON_BODY';
    case KB_NOT_FOUND = 'KB_NOT_FOUND';
    case KB_RENAME_NAME_EXISTS = 'KB_RENAME_NAME_EXISTS';
    case KB_RENAMED = 'KB_RENAMED';
    case KB_RENAMED_SUCCESSFULLY = 'KB_RENAMED_SUCCESSFULLY';
    case KB_RENAME_FAILED = 'KB_RENAME_FAILED';
    case KB_STAGE_FILE_NOT_FOUND = 'KB_STAGE_FILE_NOT_FOUND';
    case KB_STAGE_RENAME_NAME_EXISTS = 'KB_STAGE_RENAME_NAME_EXISTS';
    case KB_STAGE_RENAME_FAILED = 'KB_STAGE_RENAME_FAILED';
    case KB_FILE_RENAMED = 'KB_FILE_RENAMED';
    case KB_FILE_RENAMED_STAGE_SUCCESSFULLY = 'KB_FILE_RENAMED_STAGE_SUCCESSFULLY';
    case KB_DELETED = 'KB_DELETED';
    case KB_DIRECTORY_DELETED = 'KB_DIRECTORY_DELETED';
    case KB_FILE_DELETED = 'KB_FILE_DELETED';
    case KB_DELETE_FAILED = 'KB_DELETE_FAILED';
    case KB_PATH_REQUIRED = 'KB_PATH_REQUIRED';
    case KB_STAGE_ITEM_NOT_FOUND = 'KB_STAGE_ITEM_NOT_FOUND';
    case KB_STAGE_ITEM_DELETED_SUCCESSFULLY = 'KB_STAGE_ITEM_DELETED_SUCCESSFULLY';
    case KB_STAGE_ITEM_DELETE_FAILED = 'KB_STAGE_ITEM_DELETE_FAILED';
    case KB_INVALID_NAME = 'KB_INVALID_NAME';
    case KB_VISIBILITY_UPDATED = 'KB_VISIBILITY_UPDATED';
    case CLOUD_DIRECTORY_NOT_FOUND = 'CLOUD_DIRECTORY_NOT_FOUND';
    case CLOUD_INVALID_PATH = 'CLOUD_INVALID_PATH';
    case CLOUD_PERMISSION_NOT_ENOUGH_DELETE = 'CLOUD_PERMISSION_NOT_ENOUGH_DELETE';
    case CLOUD_DELETED = 'CLOUD_DELETED';
    case CLOUD_DELETED_SUCCESSFULLY = 'CLOUD_DELETED_SUCCESSFULLY';
    case CLOUD_NOT_FOUND = 'CLOUD_NOT_FOUND';
    case CLOUD_LIFE_PARAM_TOKEN_ONLY = 'CLOUD_LIFE_PARAM_TOKEN_ONLY';
    case CLOUD_INVALID_OTP = 'CLOUD_INVALID_OTP';
    case CLOUD_LIFETIME_RANGE = 'CLOUD_LIFETIME_RANGE';
    case CLOUD_LIFETIME_INVALID_NUMBER = 'CLOUD_LIFETIME_INVALID_NUMBER';
    case CLOUD_FILE_ACCESS_LIMITS_UPDATED = 'CLOUD_FILE_ACCESS_LIMITS_UPDATED';
    case CLOUD_INVALID_NAME = 'CLOUD_INVALID_NAME';
    case CLOUD_INVALID_DESTINATION = 'CLOUD_INVALID_DESTINATION';
    case CLOUD_ALREADY_EXISTS = 'CLOUD_ALREADY_EXISTS';
    case CLOUD_PERMISSION_NOT_ENOUGH_WRITE = 'CLOUD_PERMISSION_NOT_ENOUGH_WRITE';
    case CLOUD_FOLDER_CREATED = 'CLOUD_FOLDER_CREATED';
    case CLOUD_RENAMED = 'CLOUD_RENAMED';
    case CLOUD_MOVED = 'CLOUD_MOVED';
    case CLOUD_OPERATION_FAILED = 'CLOUD_OPERATION_FAILED';
    case CLOUD_FILE_CREATED = 'CLOUD_FILE_CREATED';
    case CLOUD_COPIED = 'CLOUD_COPIED';
    case CLOUD_CONTENT_READ = 'CLOUD_CONTENT_READ';
    case CLOUD_CONTENT_SAVED = 'CLOUD_CONTENT_SAVED';
    case CLOUD_NOT_EDITABLE = 'CLOUD_NOT_EDITABLE';
    case CLOUD_FILE_TOO_LARGE = 'CLOUD_FILE_TOO_LARGE';
    case DASHBOARD_UNSAFE_CONTENT_STOPPED = 'DASHBOARD_UNSAFE_CONTENT_STOPPED';
    case DASHBOARD_SIMPLIFIED_CHINESE_REWRITTEN = 'DASHBOARD_SIMPLIFIED_CHINESE_REWRITTEN';
    case DASHBOARD_GUARD_OFFLINE = 'DASHBOARD_GUARD_OFFLINE';
    case DASHBOARD_UPSTREAM_ERROR = 'DASHBOARD_UPSTREAM_ERROR';
    case DASHBOARD_PROTECTED_RULES = 'DASHBOARD_PROTECTED_RULES';
    case DASHBOARD_INVALID_UNLOCK_REQUEST = 'DASHBOARD_INVALID_UNLOCK_REQUEST';
    case DASHBOARD_PASSWORD_RESET_SUBMITTED = 'DASHBOARD_PASSWORD_RESET_SUBMITTED';
    case DASHBOARD_PASSWORD_RESET_NOT_FOUND = 'DASHBOARD_PASSWORD_RESET_NOT_FOUND';
    case DASHBOARD_PASSWORD_RESET_DELETED = 'DASHBOARD_PASSWORD_RESET_DELETED';
    case MANAGE_GROUP_LOCKOUT_UPDATE_BLOCKED = 'MANAGE_GROUP_LOCKOUT_UPDATE_BLOCKED';
    case MANAGE_GROUP_LOCKOUT_DELETE_BLOCKED = 'MANAGE_GROUP_LOCKOUT_DELETE_BLOCKED';
    case MANAGE_USER_UPDATED = 'MANAGE_USER_UPDATED';
    case MANAGE_USER_DELETED = 'MANAGE_USER_DELETED';
    case MANAGE_GROUP_CREATED = 'MANAGE_GROUP_CREATED';
    case MANAGE_GROUP_UPDATED = 'MANAGE_GROUP_UPDATED';
    case MANAGE_GROUP_DELETED = 'MANAGE_GROUP_DELETED';
    case FEEDBACK_NO_PERMISSION_UPDATE = 'FEEDBACK_NO_PERMISSION_UPDATE';
    case FEEDBACK_NO_PERMISSION_DELETE = 'FEEDBACK_NO_PERMISSION_DELETE';
    case PASSWORD_RESET_ACCOUNT_OR_EMAIL_REQUIRED = 'PASSWORD_RESET_ACCOUNT_OR_EMAIL_REQUIRED';
    case PASSWORD_RESET_ALREADY_SENT = 'PASSWORD_RESET_ALREADY_SENT';
    case PASSWORD_RESET_TOO_MANY_IP = 'PASSWORD_RESET_TOO_MANY_IP';
    case LOGIN_INVALID_CREDENTIALS = 'LOGIN_INVALID_CREDENTIALS';
    case LOGIN_VALIDATION_FAILED = 'LOGIN_VALIDATION_FAILED';
    case LOGIN_TOO_MANY_ATTEMPTS_EMAIL = 'LOGIN_TOO_MANY_ATTEMPTS_EMAIL';
    case LOGIN_TOO_MANY_ATTEMPTS_IP = 'LOGIN_TOO_MANY_ATTEMPTS_IP';
    case PROFILE_NOT_AUTHENTICATED = 'PROFILE_NOT_AUTHENTICATED';
    case PROFILE_LOGGED_OUT = 'PROFILE_LOGGED_OUT';
    case PROFILE_UPDATED = 'PROFILE_UPDATED';
    case PROFILE_STATIC_TOKEN_EXISTS = 'PROFILE_STATIC_TOKEN_EXISTS';
    case PROFILE_STATIC_TOKEN_NOT_FOUND = 'PROFILE_STATIC_TOKEN_NOT_FOUND';
    case PROFILE_FILE_UPLOADED = 'PROFILE_FILE_UPLOADED';
    case PROFILE_ACCOUNT_DELETED = 'PROFILE_ACCOUNT_DELETED';
    case PROFILE_CHAT_COMPLETION_UNAUTHORIZED = 'PROFILE_CHAT_COMPLETION_UNAUTHORIZED';
    case PROFILE_CHAT_COMPLETION_MISSING_FIELDS = 'PROFILE_CHAT_COMPLETION_MISSING_FIELDS';
    case PROFILE_MODEL_NOT_FOUND = 'PROFILE_MODEL_NOT_FOUND';
    case PROFILE_MESSAGE_FIELD_INVALID = 'PROFILE_MESSAGE_FIELD_INVALID';
    case PROFILE_PASSWORD_UPDATED = 'PROFILE_PASSWORD_UPDATED';
    case PROFILE_PASSWORD_UPDATE_FAILED = 'PROFILE_PASSWORD_UPDATE_FAILED';
    case NOTICE_UNPUBLISH_AT_INVALID = 'NOTICE_UNPUBLISH_AT_INVALID';

    // Generic fallbacks for dynamic (non-translated) error messages, e.g.
    // validator/exception output that cannot map to a single translation key.
    case INTERNAL_ERROR = 'INTERNAL_ERROR';
    case FILE_ACCESS_LIMIT_EXCEEDED = 'FILE_ACCESS_LIMIT_EXCEEDED';
    case MODEL_CONFIGURATION_FAILED = 'MODEL_CONFIGURATION_FAILED';
}
