services:
  agent-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - executor-builder
    environment:
      CUSTOM_EXECUTOR_PATH: ./agent/main.py
      EXECUTOR_ACCESS_CODE: .tool/skyscope/agent
      EXECUTOR_NAME: Agent
      EXECUTOR_IMAGE: iteration.png # Refer to src/multi-chat/public/images
      EXECUTOR_ORDER: 999010
      TRANSFORMERS_OFFLINE: ${TRANSFORMERS_OFFLINE:-0} # For embedding model
    command: [
      # "--api_base_url", "http://${DOMAIN_NAME}/",
      "--log", "debug",
    ]