services:
  chatgpt-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - skyscope-executor-builder
    environment:
      EXECUTOR_TYPE: chatgpt
      EXECUTOR_ACCESS_CODE: .model/openai/chatgpt
      EXECUTOR_NAME: ChatGPT
      EXECUTOR_ORDER: 401100
      EXECUTOR_IMAGE: chatgpt.png # Refer to src/multi-chat/public/images
    command: [
      #"--temperature", "0.2"
    ]