services:
  dall-e-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - skyscope-executor-builder
    environment:
      CUSTOM_EXECUTOR_PATH: ./image_generation/dall_e.py
      EXECUTOR_ACCESS_CODE: .model/openai/dall-e
      EXECUTOR_NAME: DALL-E
      EXECUTOR_ORDER: 421000
      EXECUTOR_IMAGE: dall-e.png # Refer to src/multi-chat/public/images
    command: []