services:
  web:
    environment:
      DEBUG_ENDPOINT: "true"
  skyscope-chat:
    environment:
      APP_ENV: development
      APP_DEBUG: true
  db-ui:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - skyscope-network