services:
  executor-base:
    image: skyscopeai/model-executor
    volumes: [
      "skyscope-root:/var/skyscope/docker/root:rw", # The root of Skyscope filesystem hierarchy to store user-uploaded data during runtime.
      "~/.cache/huggingface:/root/.cache/huggingface",
      "~/.cache/torch:/root/.cache/torch",
      "~/.cache/whisper_s2t:/root/.cache/whisper_s2t",
    ]
    extra_hosts:
      - "localhost:host-gateway"
    restart: unless-stopped
    networks: ["skyscope-network"]
    # Uncomment to use NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ['0']
    #         capabilities: [gpu]