services:
  llamacpp-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - skyscope-executor-builder
    environment:
      EXECUTOR_TYPE: llamacpp
      EXECUTOR_ACCESS_CODE: taide-4bit
      EXECUTOR_NAME: TAIDE 4bit
      EXECUTOR_IMAGE: llamacpp.png # Refer to src/multi-chat/public/images
    command: ["--model_path", "/var/model/taide-4bit.gguf", "--ngl", "-1", "--temperature", "0"]
    volumes: ["/path/to/taide/model.gguf:/var/model/taide-4bit.gguf"]