services:
  skyscope-chat:
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD_FILE: /run/secrets/db-password
      DB_DATABASE: ${DB_DATABASE}
    secrets:
      - db-password

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - skyscope-pgsql-data:/var/lib/postgresql/data
    secrets:
      - db-password
    networks:
      - skyscope-network

  # db-ui:
  #   image: adminer
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - skyscope-network

volumes:
  skyscope-pgsql-data: {}

secrets:
  db-password:
    file: ../.db-password