services:
  pipe-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - skyscope-executor-builder
    environment:
      CUSTOM_EXECUTOR_PATH: ./pipe/main.py
      EXECUTOR_ACCESS_CODE: .tool/skyscope/pipe
      EXECUTOR_NAME: Pipe
      EXECUTOR_IMAGE: pipe.png # Refer to src/multi-chat/public/images
      EXECUTOR_ORDER: 999999
      TRANSFORMERS_OFFLINE: ${TRANSFORMERS_OFFLINE:-0} # For embedding model
    command: [
      "--api_base_url", "http://${DOMAIN_NAME}/",
      "--log", "debug",
    ]