services:
  search-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - skyscope-executor-builder
    environment:
      CUSTOM_EXECUTOR_PATH: ./docqa/searchqa.py
      EXECUTOR_ACCESS_CODE: .tool/skyscope/search
      EXECUTOR_NAME: Search
      EXECUTOR_IMAGE: search-qa.png # Refer to src/multi-chat/public/images
      EXECUTOR_ORDER: 990020
      EXECUTOR_CREATE_BOT: false
      TRANSFORMERS_OFFLINE: ${TRANSFORMERS_OFFLINE:-0} # For embedding model
    command: [
      "--log", "debug",
      "--api_base_url", "http://web/",
      "--model", ".bot/.default",
      "--google_api_key", "<YOUR_GOOGLE_API_KEY>",
      "--google_cse_id", "<YOUR_GOOGLE_CUSTOM_SEARCH_ENGINE_ID>",
      #"--advanced_params", "site:example.tw site:example.com"
      ]