services:
  uploader-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - skyscope-executor-builder
    environment:
      CUSTOM_EXECUTOR_PATH: ./uploader/main.py
      EXECUTOR_ACCESS_CODE: .tool/skyscope/uploader
      EXECUTOR_NAME: Uploader
      EXECUTOR_ORDER: 999020
      EXECUTOR_CREATE_BOT: false
      EXECUTOR_IMAGE: upload.png # Refer to src/multi-chat/public/images
    command: [
      "--api_base_url", "http://web/",
      "--log", "debug"
    ]