services:
  whisper-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - skyscope-executor-builder
    environment:
      CUSTOM_EXECUTOR_PATH: ./speech_recognition/main.py
      EXECUTOR_ACCESS_CODE: .model:whisper/
      EXECUTOR_NAME: Whisper
      EXECUTOR_IMAGE: whisper.png # Refer to src/multi-chat/public/images
      EXECUTOR_ORDER: 331000
      EXECUTOR_CREATE_BOT: false
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}