name: Build Windows Installer

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove GitHub Actions extra header
        run: |
          git config --unset "http.https://github.com/.extraheader"

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Install Inno Setup extra language files
        run: |
          $baseUri = 'https://raw.githubusercontent.com/skyscopeai/issrc/main/Files/Languages'
          $langPath = "$env:ProgramFiles (x86)\Inno Setup 6\Languages"
          $files = @{
            Default = "..\Default.isl"
            Czech = "Czech.isl"
            French = "French.isl"
            German = "German.isl"
            Japanese = "Japanese.isl"
            Korean = "Korean.isl"
            ChineseTraditional = "Unofficial/ChineseTraditional.isl"
            ChineseSimplified = "Unofficial/ChineseSimplified.isl"
          }
          New-Item -ItemType Directory -Path $langPath -Force | Out-Null
          foreach ($name in $files.Keys) {
            Invoke-WebRequest "$baseUri/$($files[$name])" -OutFile "$langPath\$name.isl"
          }

      - name: Download Gemma-3B model file
        run: |
          $url = "https://huggingface.co/tetf/gemma-3-1b-it-qat-q4_0-GGUF/resolve/main/gemma-3-1b-it-q4_0.gguf?download=true"
          $destDir = "windows/executors/gemma3-1b"
          New-Item -ItemType Directory -Path $destDir -Force | Out-Null
          Invoke-WebRequest $url -OutFile "$destDir\gemma-3-1b-it-q4_0.gguf"

      - name: Copy _run.bat to run.bat in executors
        run: |
          Get-ChildItem windows/executors -Directory -Recurse | ForEach-Object {
            $src = "$($_.FullName)\_run.bat"
            $dst = "$($_.FullName)\run.bat"
            if (Test-Path $src) { Copy-Item $src $dst -Force }
          }

      - name: Copy requirements.txt.lock to src
        run: Copy-Item windows\src\version_patch\11.8\windows\src\requirements.txt.lock windows\src -Force

      - name: Compile installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: scripts/windows-setup-files/Skyscope-AIOS-Online-Installer.iss
          options: /O+

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Skyscope-GenAI-OS-${{ github.ref_name }}${{ steps.commit.outputs.short }}
          path: scripts/windows-setup-files/Skyscope-GenAI-OS.exe